/******************************************************************************
* This file was generated by ZenStack CLI.
******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import type { Prisma } from "@prisma/client";
import { type GetNextArgs, type QueryOptions, type InfiniteQueryOptions, type MutationOptions, type PickEnumerable } from '@zenstackhq/swr/runtime';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
import * as request from '@zenstackhq/swr/runtime';

export function useCreateEntry(options?: MutationOptions<Prisma.EntryGetPayload<Prisma.EntryCreateArgs> | undefined, unknown, Prisma.EntryCreateArgs>) {
    const mutation = request.useModelMutation('Entry', 'POST', 'create', metadata, options, true);
    return {
        ...mutation,
        trigger: <T extends Prisma.EntryCreateArgs>(args: Prisma.SelectSubset<T, Prisma.EntryCreateArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.EntryGetPayload<T> | undefined>;
        }
    };
}

export function useCreateManyEntry(options?: MutationOptions<Prisma.BatchPayload, unknown, Prisma.EntryCreateManyArgs>) {
    const mutation = request.useModelMutation('Entry', 'POST', 'createMany', metadata, options, false);
    return {
        ...mutation,
        trigger: <T extends Prisma.EntryCreateManyArgs>(args: Prisma.SelectSubset<T, Prisma.EntryCreateManyArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.BatchPayload>;
        }
    };
}

export function useFindManyEntry<T extends Prisma.EntryFindManyArgs>(args?: Prisma.SelectSubset<T, Prisma.EntryFindManyArgs>, options?: QueryOptions<Array<Prisma.EntryGetPayload<T> & { $optimistic?: boolean }>>) {
    return request.useModelQuery('Entry', 'findMany', args, options);
}

export function useInfiniteFindManyEntry<T extends Prisma.EntryFindManyArgs, R extends Array<Prisma.EntryGetPayload<T>>>(getNextArgs: GetNextArgs<Prisma.SelectSubset<T, Prisma.EntryFindManyArgs> | undefined, R>, options?: InfiniteQueryOptions<Array<Prisma.EntryGetPayload<T>>>) {
    return request.useInfiniteModelQuery('Entry', 'findMany', getNextArgs, options);
}

export function useFindUniqueEntry<T extends Prisma.EntryFindUniqueArgs>(args?: Prisma.SelectSubset<T, Prisma.EntryFindUniqueArgs>, options?: QueryOptions<Prisma.EntryGetPayload<T> & { $optimistic?: boolean }>) {
    return request.useModelQuery('Entry', 'findUnique', args, options);
}

export function useFindFirstEntry<T extends Prisma.EntryFindFirstArgs>(args?: Prisma.SelectSubset<T, Prisma.EntryFindFirstArgs>, options?: QueryOptions<Prisma.EntryGetPayload<T> & { $optimistic?: boolean }>) {
    return request.useModelQuery('Entry', 'findFirst', args, options);
}

export function useUpdateEntry(options?: MutationOptions<Prisma.EntryGetPayload<Prisma.EntryUpdateArgs> | undefined, unknown, Prisma.EntryUpdateArgs>) {
    const mutation = request.useModelMutation('Entry', 'PUT', 'update', metadata, options, true);
    return {
        ...mutation,
        trigger: <T extends Prisma.EntryUpdateArgs>(args: Prisma.SelectSubset<T, Prisma.EntryUpdateArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.EntryGetPayload<T> | undefined>;
        }
    };
}

export function useUpdateManyEntry(options?: MutationOptions<Prisma.BatchPayload, unknown, Prisma.EntryUpdateManyArgs>) {
    const mutation = request.useModelMutation('Entry', 'PUT', 'updateMany', metadata, options, false);
    return {
        ...mutation,
        trigger: <T extends Prisma.EntryUpdateManyArgs>(args: Prisma.SelectSubset<T, Prisma.EntryUpdateManyArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.BatchPayload>;
        }
    };
}

export function useUpsertEntry(options?: MutationOptions<Prisma.EntryGetPayload<Prisma.EntryUpsertArgs> | undefined, unknown, Prisma.EntryUpsertArgs>) {
    const mutation = request.useModelMutation('Entry', 'POST', 'upsert', metadata, options, true);
    return {
        ...mutation,
        trigger: <T extends Prisma.EntryUpsertArgs>(args: Prisma.SelectSubset<T, Prisma.EntryUpsertArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.EntryGetPayload<T> | undefined>;
        }
    };
}

export function useDeleteEntry(options?: MutationOptions<Prisma.EntryGetPayload<Prisma.EntryDeleteArgs> | undefined, unknown, Prisma.EntryDeleteArgs>) {
    const mutation = request.useModelMutation('Entry', 'DELETE', 'delete', metadata, options, true);
    return {
        ...mutation,
        trigger: <T extends Prisma.EntryDeleteArgs>(args: Prisma.SelectSubset<T, Prisma.EntryDeleteArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.EntryGetPayload<T> | undefined>;
        }
    };
}

export function useDeleteManyEntry(options?: MutationOptions<Prisma.BatchPayload, unknown, Prisma.EntryDeleteManyArgs>) {
    const mutation = request.useModelMutation('Entry', 'DELETE', 'deleteMany', metadata, options, false);
    return {
        ...mutation,
        trigger: <T extends Prisma.EntryDeleteManyArgs>(args: Prisma.SelectSubset<T, Prisma.EntryDeleteManyArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.BatchPayload>;
        }
    };
}

export function useAggregateEntry<T extends Prisma.EntryAggregateArgs>(args?: Prisma.Subset<T, Prisma.EntryAggregateArgs>, options?: QueryOptions<Prisma.GetEntryAggregateType<T>>) {
    return request.useModelQuery('Entry', 'aggregate', args, options);
}

export function useGroupByEntry<T extends Prisma.EntryGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<T>>, Prisma.Extends<'take', Prisma.Keys<T>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.EntryGroupByArgs['orderBy'] } : { orderBy?: Prisma.EntryGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<T['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<T['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]>(args?: Prisma.SubsetIntersection<T, Prisma.EntryGroupByArgs, OrderByArg> & InputErrors, options?: QueryOptions<{} extends InputErrors ?
        Array<PickEnumerable<Prisma.EntryGroupByOutputType, T['by']> &
            {
                [P in ((keyof T) & (keyof Prisma.EntryGroupByOutputType))]: P extends '_count'
                ? T[P] extends boolean
                ? number
                : Prisma.GetScalarType<T[P], Prisma.EntryGroupByOutputType[P]>
                : Prisma.GetScalarType<T[P], Prisma.EntryGroupByOutputType[P]>
            }
        > : InputErrors>) {
    return request.useModelQuery('Entry', 'groupBy', args, options);
}

export function useCountEntry<T extends Prisma.EntryCountArgs>(args?: Prisma.Subset<T, Prisma.EntryCountArgs>, options?: QueryOptions<T extends { select: any; } ? T['select'] extends true ? number : Prisma.GetScalarType<T['select'], Prisma.EntryCountAggregateOutputType> : number>) {
    return request.useModelQuery('Entry', 'count', args, options);
}

export function useCheckEntry(args: { operation: PolicyCrudKind; where?: { id?: string; title?: string; pathPrefix?: string; readingPath?: string; entryType?: string; authorId?: string }; }, options?: QueryOptions<boolean>) {
    return request.useModelQuery('Entry', 'check', args, options);
}
